[package]
name = "mechvibes-dx"
version = "0.1.0"
authors = ["Hải Nguyễn <hainguyen.ts13@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.6.1", features = ["router"] }
env_logger = "0.11.6"
futures-timer = "3.0.3"
lucide-dioxus = { version = "2.1.0" , features = ["all-icons"] }
once_cell = "1.21.3"
rand = "0.9.0"
rdev = "0.5.3"
rodio = "0.20.1"
serde = "1.0.218"
serde_json = "1.0.140"

[features]
default = ["dioxus/desktop"]
desktop = ["dioxus/desktop"]

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
